// Generates src/palettes.rs from .dev/zeron/src/themes.css.
// Run: node scripts/gen-themes.mjs
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync(new URL("../.dev/zeron/src/themes.css", import.meta.url), "utf8");

// --- oklch -> sRGB ---
function oklchToSrgb(l, c, h) {
  const hr = (h * Math.PI) / 180;
  const a = c * Math.cos(hr),
    b = c * Math.sin(hr);
  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.291485548 * b;
  const l3 = l_ ** 3,
    m3 = m_ ** 3,
    s3 = s_ ** 3;
  let r = 4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3;
  let g = -1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3;
  let bl = -0.0041960863 * l3 - 0.7034186147 * m3 + 1.707614701 * s3;
  const gam = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);
  r = gam(r);
  g = gam(g);
  bl = gam(bl);
  const c255 = (x) => Math.round(Math.min(1, Math.max(0, x)) * 255);
  return [c255(r), c255(g), c255(bl)];
}
const hex = ([r, g, b]) => "0x" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
const mixRgb = (a, t, b) => a.map((v, i) => Math.round(v * t + b[i] * (1 - t)));

// --- parse ---
function block(sel) {
  const esc = sel.replace(/[.*:]/g, (m) => "\\" + m);
  const m = css.match(new RegExp(esc + "\\s*\\{([^}]*)\\}"));
  if (!m) throw new Error("selector not found: " + sel);
  const tokens = {};
  for (const mm of m[1].matchAll(
    /--([\w-]+):\s*oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)(?:\s*\/\s*([\d.]+)%)?/g,
  )) {
    tokens[mm[1]] = { l: +mm[2], c: +mm[3], h: +mm[4], a: mm[5] ? +mm[5] / 100 : 1 };
  }
  return tokens;
}
const col = (t, name) => {
  const v = t[name];
  if (!v) throw new Error("missing token " + name);
  return oklchToSrgb(v.l, v.c, v.h);
};

const THEME_DEFS = [
  ["default", "Default", "Чистый минималистичный стиль", ".default", ".dark.default"],
  ["t3-chat", "T3 Chat", "Стиль современного чат-интерфейса", ".t3-chat", ".t3-chat.dark"],
  ["claymorphism", "Claymorphism", "Мягкий глиняный вид", ".claymorphism", ".claymorphism.dark"],
  ["claude", "Claude", "Тема в духе Anthropic Claude", ".claude", ".claude.dark"],
  ["graphite", "Graphite", "Тёмный и строгий", ".graphite", ".graphite.dark"],
  ["amethyst-haze", "Amethyst Haze", "Фиолетовый оттенок", ".amethyst-haze", ".dark.amethyst-haze"],
  ["vercel", "Vercel", "Дизайн в стиле Vercel", ".vercel", ".dark.vercel"],
];

function palette(t) {
  const bg = col(t, "background"),
    fg = col(t, "foreground"),
    pop = col(t, "popover");
  const accent = col(t, "primary"),
    sidebar = col(t, "sidebar");
  return `Palette {
        bg: ${hex(bg)},
        fg: ${hex(fg)},
        muted_fg: ${hex(col(t, "muted-foreground"))},
        border: ${hex(mixRgb(fg, 0.12, bg))},
        accent: ${hex(accent)},
        accent_fg: ${hex(col(t, "primary-foreground"))},
        accent_dim: ${hex(mixRgb(accent, 0.72, bg))},
        secondary: ${hex(col(t, "secondary"))},
        card: ${hex(col(t, "card"))},
        popover: ${hex(pop)},
        sidebar_bg: ${hex(sidebar)},
        sidebar_divider: ${hex(mixRgb(fg, 0.08, sidebar))},
        destructive: ${hex(col(t, "destructive"))},
        warn: ${hex(col(t, "chart-4"))},
        success: ${hex(col(t, "chart-3"))},
        qe_chip_bg: ${hex(mixRgb(accent, 0.3, pop))},
        qe_chip_fg: ${hex(mixRgb(accent, 0.75, fg))},
    }`;
}

let out = `//! GENERATED by scripts/gen-themes.mjs from .dev/zeron/src/themes.css — do not edit by hand.

use crate::theme::Palette;

pub struct ThemeDef {
    #[allow(dead_code)]
    pub key: &'static str,
    pub name: &'static str,
    pub desc: &'static str,
    pub light: Palette,
    pub dark: Palette,
}

pub const THEMES: &[ThemeDef] = &[
`;
for (const [key, name, desc, lsel, dsel] of THEME_DEFS) {
  out += `    ThemeDef {
        key: "${key}",
        name: "${name}",
        desc: "${desc}",
        light: ${palette(block(lsel))},
        dark: ${palette(block(dsel))},
    },
`;
}
out += `];
`;

writeFileSync(new URL("../src/palettes.rs", import.meta.url), out);
console.log("wrote src/palettes.rs");
